# Generated by Django 6.0.4 on 2026-05-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0003_alter_reserva_paciente'),
        ('usuarios', '0003_alter_kinesiologo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('sena', 'Seña (50%)'), ('total', 'Total')], max_length=10)),
                ('metodo_pago', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('monto_total_clase', models.DecimalField(decimal_places=2, help_text='Precio completo de la clase al momento de pagar', max_digits=10)),
                ('monto_abonado', models.DecimalField(decimal_places=2, help_text='Lo que efectivamente pagó: 50% si es seña, 100% si es total', max_digits=10)),
                ('id_transaccion_externa', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='usuarios.cliente')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Pago de Reserva',
                'ordering': ['-creado_en'],
            },
        ),
    ]
