# Generated by Django 6.0.4 on 2026-05-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoreserva',
            name='monto_devuelto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto devuelto al cliente en caso de cancelación', max_digits=10),
        ),
    ]
