# Generated by Django 6.0.4 on 2026-05-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pagoreserva_monto_devuelto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoreserva',
            name='metodo_pago',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('tarjeta', 'Tarjeta'), ('saldo', 'Saldo a Favor')], max_length=20),
        ),
    ]
