# Generated by Django 6.0.4 on 2026-06-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pagoreserva_metodo_pago'),
        ('usuarios', '0004_cliente_saldo_a_favor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('efectivo', 'Efectivo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('periodo', models.DateField(help_text='Primer día del mes que cubre esta cuota')),
                ('id_transaccion_externa', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_cuota', to='usuarios.cliente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_registradas', to='usuarios.administrador')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'ordering': ['-creado_en'],
            },
        ),
    ]
