# Generated by Django 6.0.4 on 2026-07-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_ajustar_configuracion_cuota_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuota',
            name='metodo_pago',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('tarjeta', 'Tarjeta')], max_length=20),
        ),
    ]
