# Generated by Django 6.0.4 on 2026-04-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tren_inferior', 'Tren Inferior'), ('zona_media', 'Zona Media'), ('tren_superior', 'Tren Superior')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('kinesiologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='usuarios.kinesiologo')),
            ],
            options={
                'verbose_name': 'Clase',
                'ordering': ['dia', 'hora_inicio'],
                'unique_together': {('dia', 'hora_inicio', 'kinesiologo')},
            },
        ),
    ]
