# Generated by Django 6.0.4 on 2026-05-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='sala',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
