# Generated by Django 6.0.4 on 2026-05-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_clase_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
