# Generated by Django 6.0.4 on 2026-05-28 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_clase_fecha_clase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together=set(),
        ),
    ]
