# Generated by Django 6.0.4 on 2026-05-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_clase_fecha_clase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['fecha_clase', 'hora_inicio'], 'verbose_name': 'Clase'},
        ),
    ]
