# Generated by Django 6.0.4 on 2026-06-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_alter_clase_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together=set(),
        ),
    ]
