# Generated by Django 6.0.4 on 2026-05-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kinesiologo',
            name='especialidad',
        ),
    ]
