# Generated by Django 6.0.4 on 2026-05-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_kinesiologo_especialidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kinesiologo',
            options={'verbose_name': 'Kinesiologo'},
        ),
    ]
