# Generated by Django 6.0.4 on 2026-06-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_kinesiologo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo_a_favor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
