# Generated by Django 6.0.4 on 2026-06-24 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cliente_saldo_a_favor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='El DNI debe contener entre 7 y 8 dígitos numéricos.', regex='^\\d{7,8}$')]),
        ),
    ]
