# Generated by Django 6.0.4 on 2026-07-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_alta_abonado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
