# Generated by Django 6.0.4 on 2026-06-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0007_alter_reserva_estado'),
        ('usuarios', '0005_alter_usuario_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('kinesiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_evolucion', to='usuarios.kinesiologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_evolucion', to='usuarios.cliente')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_evolucion', to='reservas.reserva')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
