# Generated by Django 6.0.4 on 2026-05-17 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='saldo_a_favor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_pago',
            field=models.CharField(choices=[('TOTAL', 'Pago Total'), ('SENIA', 'Seña')], default='TOTAL', max_length=10),
        ),
    ]
