# Generated by Django 6.0.4 on 2026-05-21 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_fecha_reserva_reserva_saldo_a_favor_and_more'),
        ('usuarios', '0003_alter_kinesiologo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuarios.cliente'),
        ),
    ]
