# Generated by Django 6.0.4 on 2026-05-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='saldo_a_favor',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tipo_pago',
        ),
    ]
