# Generated by Django 6.0.4 on 2026-05-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_fecha_reserva_reserva_saldo_a_favor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDIENTE', 'Pendiente de Pago'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=20),
        ),
    ]
