# Generated by Django 6.0.4 on 2026-06-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_asistencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodo_asistencia',
            field=models.CharField(blank=True, choices=[('QR', 'QR'), ('MANUAL', 'Manual')], max_length=10, null=True),
        ),
    ]
